# Generated by Django 5.1 on 2024-08-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='code',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='account',
            name='code_confirm',
            field=models.CharField(max_length=6),
        ),
    ]
